### ISSUE TITLE
Create new architecture for the project 

### ISSUE THREAD

**Issue by Vquillien** [orbisgis/ogc-custom-jaxb#9]
I can't create a test java in this project. There should be one part for files xsd and one part for test files on the classes generate by JaxB.

**Comment by ebocher** [comment]
Have a look here https://github.com/orbisgis/orbisdata/issues/1 this is the main repository to host the java binding and all tests.

@SPalominos

**Comment by SPalominos** [comment]
@ebocher Yes, you're right.
@Vquillien You'd better do like @ebocher said, creating a module containing two sub-module (binding and test).

**Comment by SPalominos** [comment]
So, as the test to the binding of the java classes can not be in the same module ad the xsd+binding files (the generated classes are in the target directory, so the test can not use it), the project should look like : 

ogc-custom : main project
 -> ogc-custom-model : module which contains the xsd and the binding.xjb file and which generated the java classes.
 -> ogc-custom-test : module which contains the test to run to check the binding.
